config/routes.rb
Rails.application.routes.draw do
  get 'goals/new'

  get 'goals/edit'

  get 'goals/show'

  resources :users
  resource :session
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :details, :user_id, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  has_many :goals

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
  end

  def edit
  end

  def show
  end

  def create
  end

  def destroy

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
    params[:user][:username],
    params[:user][:password]
    )
    
    if user
      login(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)

    if user.save
      login(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Goals#edit</h1>
<p>Find me in app/views/goals/edit.html.erb</p>

app/views/goals/new.html.erb
<h1>Goals#new</h1>
<p>Find me in app/views/goals/new.html.erb</p>

app/views/goals/show.html.erb
<h1>Goals#show</h1>
<p>Find me in app/views/goals/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= current_user.username %>
    <%= button_to "Log Out", session_url, method: :delete %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    username
    <input type="text" name="user[username]" value="">
  </label>
  <label>
    password
    <input type="text" name="user[password]" value="">
  </label>

  <input type="submit" value="Create User">
</form>

app/views/users/show.html.erb
<h2>Homepage</h2>